# Generated by Django 5.2 on 2026-07-07 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.categorymodel')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValueModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.productattributemodel')),
            ],
            options={
                'verbose_name': 'Product Attribute Value',
                'verbose_name_plural': 'Product Attribute Values',
                'ordering': ['attribute__name', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.brandmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.categorymodel')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productmodel')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecificationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.productmodel')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAttributeValueModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_attribute_values', to='product.productattributevaluemodel')),
            ],
            options={
                'verbose_name': 'Product Variant Attribute Value',
                'verbose_name_plural': 'Product Variant Attribute Values',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('price_rial', models.BigIntegerField()),
                ('compare_at_price_rial', models.BigIntegerField(blank=True, null=True)),
                ('cost_price_rial', models.BigIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('reserved_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('attributes_snapshot', models.JSONField(blank=True, default=dict)),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_values', models.ManyToManyField(blank=True, related_name='variants', through='product.ProductVariantAttributeValueModel', to='product.productattributevaluemodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.productmodel')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productvariantattributevaluemodel',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_values', to='product.productvariantmodel'),
        ),
        migrations.AddConstraint(
            model_name='productattributevaluemodel',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='unique_product_attribute_value'),
        ),
        migrations.AddConstraint(
            model_name='productattributevaluemodel',
            constraint=models.UniqueConstraint(fields=('attribute', 'slug'), name='unique_product_attribute_slug'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['status'], name='product_pro_status_a3a58f_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['is_active'], name='product_pro_is_acti_4270de_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['is_featured'], name='product_pro_is_feat_341795_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['category', 'status'], name='product_pro_categor_f2c30c_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['slug'], name='product_pro_slug_a6362c_idx'),
        ),
        migrations.AddIndex(
            model_name='productimagemodel',
            index=models.Index(fields=['product', 'is_primary'], name='product_pro_product_2e3732_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantmodel',
            index=models.Index(fields=['product', 'is_active'], name='product_pro_product_09e8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantmodel',
            index=models.Index(fields=['sku'], name='product_pro_sku_f4f3de_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantmodel',
            index=models.Index(fields=['price_rial'], name='product_pro_price_r_3a8de9_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariantattributevaluemodel',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute_value'), name='unique_variant_attribute_value_link'),
        ),
    ]
