# Generated by Django 5.2 on 2026-07-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='error_code_paid',
            new_name='error_code',
        ),
    ]
